version: '3.4'

services:
    api:
        image: compose-api:latest
        restart: on-failure
        depends_on:
            - db
        build:
            context: .
        ports:
            - "5500:80"
        environment:
            ConnectionStrings__Defaultconnection: "Data Source=db;Initial Catalog=MigartionsWithCompose;User id=sa;Password=PaSSw0rd"
        
    db:
        image: mcr.microsoft.com/mssql/server
        restart: on-failure
        ports:
            - "14433:1433"
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "PaSSw0rd"
        volumes:
            - ./data:/var/opt/mssql/data