version: '3.4'

services:
    api:
        image: compose-api:latest
        restart: on-failure
        depends_on:
            - db
            - redis
        build:
            context: .
        ports:
            - "5500:80"
        environment:
            ConnectionStrings__Defaultconnection: "Server=db;Database=SportsCompetition;User id=sa;Password=PaSSw0rd"
            ConnectionStrings__Redis: "redis"
        
    db:
        image: mcr.microsoft.com/mssql/server
        restart: on-failure
        ports:
            - "14433:1433"
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "PaSSw0rd"
        volumes:
            - ./data:/var/opt/mssql/data

    redis:
        image: redis:latest
        restart: on-failure